// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestApp.Data;

#nullable disable

namespace TestApp.Data.Migrations
{
    [DbContext(typeof(OmniSiteDbContext))]
    [Migration("20220602195245_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TestApp.Domain.OmniSiteData", b =>
                {
                    b.Property<string>("SimNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("ActiveFlag")
                        .HasColumnType("bit");

                    b.Property<string>("Msisdn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Protocol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ProviderActive")
                        .HasColumnType("bit");

                    b.Property<string>("StationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SimNumber");

                    b.ToTable("OmniSiteDataPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
